### ISSUE TITLE
Need to grab OAUTH User and Secret tokens at login

### ISSUE THREAD

**Issue by csharpfritz** [csharpfritz/TwitterFriendsList#1]
Needs this so we can make follow-up requests to Twitter

https://github.com/linvi/tweetinvi

 https://github.com/linvi/tweetinvi/tree/master/Examplinvi.ASP.NET.Core

**Comment by andreujuanc** [comment]
Looks like tweetinvi does not play well with builtin auth.

Maybe setting what claims you want to receive while authenticating. Setting twitterOptions.ClaimActions might be a good hint. 

Issue then really is, where to get the name or namespace for those claims.

**Comment by andreujuanc** [comment]
Ok, Got it.

So janos was right, it was an event all along. Not OnTicketReceived but OnCreatingTicket .

```
twitterOptions.Events.OnCreatingTicket = ct =>
{
     //So here we get access token and secret. Next move would be to store it somewhere, 
     //For example, adding it to claims.
     //ct.AccessToken
     //ct.AccessTokenSecret
      if (ct.Principal.Identity is ClaimsIdentity;claimsIdentity claimsIdentity)
        {
           claimsIdentity.AddClaim(new Claim("urn:twitter:accesstoken", ct.AccessToken));
           claimsIdentity.AddClaim(new Claim("urn:twitter:accesstokensecret", ct.AccessTokenSecret));
       }
       return Task.CompletedTask;
};
```

EDIT: Claims does not get persisted, somehow.

**Comment by parithon** [comment]
If you are saving the tokens you would do the following within a Page to retrieve them:

```c#
if (User.Identity.IsAuthenticated)
{
    string accessToken = await HttpContext.GetTokenAsync("access_token");
    string idToken = await HttpContext.GetTokenAsync("id_token");
}
```

**Comment by parithon** [comment]
To save the AuthenticationTokens you would need to do the following.

In the `ExternalLogin.OnGetCallbackAsync` method you would add the following:

```c#
var info = await _signInManager.GetExternalLoginInfoAsync();
if (info == null)
{
  ErrorMessage = "Error loading external login information.";
  return RedirectToPage("./Login", new { ReturnUrl = returnUrl });
}

// Add this line of code which saves the tokens to the DB
await _signInManager.UpdateExternalAuthenticationTokensAsync(info);
```

Then you would access the saved tokens in the Page by injecting `UserManager<IdentityUser>` and using the following code:

```c#
if (User.Identity.IsAuthenticated)
{
  var user = await _userManager.GetUserAsync(User);
  var accessToken = await _userManager.GetAuthenticationTokenAsync(user, "Twitter", "access_token");
  var accessTokenSecret = await _userManager.GetAuthenticationTokenAsync(user, "Twitter", "access_token_secret");
}
```

EDIT: Added a comment to make it clear which line is added to the `OnGetCallbackAsync` method.

**Comment by csharpfritz** [comment]
This works!  Thanks for the updates...

**Comment by andreujuanc** [comment]
Wow `UpdateExternalAuthenticationTokensAsync` is super dark. Thanks!
